Repository f-lab-edu/foody-lab, pull requests merged in 2022-11, with the labels that each got.

#38 Issue 17 새로운기능 테스트용 데이터베이스 h2 환경 구성하기
  build.gradle
  docker-compose.yml
  src/main/java/app/foodylab/adaptor/controller/CustomerController.java
  src/main/java/app/foodylab/adaptor/controller/UserController.java
  src/main/java/app/foodylab/adaptor/infra/mapper/CustomerMapper.java
  src/main/java/app/foodylab/adaptor/infra/mapper/UserMapper.java
  src/main/java/app/foodylab/adaptor/infra/mybatis/config/MybatisConfig.java
  src/main/java/app/foodylab/adaptor/infra/mybatis/repository/customer/CustomerMybatisRepository.java
  src/main/java/app/foodylab/adaptor/infra/mybatis/repository/user/UserMybatisRepository.java
  src/main/java/app/foodylab/application/customer/service/CustomerService.java
  src/main/java/app/foodylab/application/user/service/UserService.java
  src/main/java/app/foodylab/domain/customer/Customer.java
  src/main/java/app/foodylab/domain/customer/repository/CustomerRepository.java
  src/main/java/app/foodylab/domain/order/Order.java
  src/main/java/app/foodylab/domain/user/repository/UserRepository.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/docker/seed.sql
  src/main/resources/mybatis/mapper/CustomerDao.xml
  src/test/java/app/foodylab/application/customer/CustomerServiceTest.java
  src/test/java/app/foodylab/application/user/UserServiceTest.java
  src/test/java/app/foodylab/domain/order/OrderTest.java
  src/test/resources/application.yml
  src/testFixtures/java/app/foodylab/CustomerFixture.java
  src/testFixtures/java/app/foodylab/UserFixture.java
Labels: 새로운 기능

#42 롬복을 이용해 생성자 주입 적용
  src/main/java/app/foodylab/adaptor/controller/CustomerController.java
Labels: 리팩토링

#48 Issue 45 bugfix main에 merge된 브랜치 내용을 dev로 가져오기
  build.gradle
  src/main/java/app/foodylab/adaptor/CustomerDto.java
  src/main/java/app/foodylab/application/UserMapper.java
Labels: bug

#49 Issue 47 새로운기능 jacoco 도입하기
  .github/workflows/gradleCI.yml
  .github/workflows/jacoco.yml
  build.gradle
Labels: 새로운 기능

#46 Issue 32 리팩토링 할인 전략과 쿠폰 분리하기
  src/main/java/app/foodylab/application/coupon/Coupon.java
  src/main/java/app/foodylab/application/payment/service/PayService.java
  src/main/java/app/foodylab/domain/coupon/Coupon.java
  src/main/java/app/foodylab/domain/coupon/CouponType.java
  src/main/java/app/foodylab/domain/coupon/PriceCoupon.java
  src/main/java/app/foodylab/domain/discount/DiscountPolicy.java
  src/main/java/app/foodylab/domain/discount/PriceDiscountPolicy.java
  src/main/java/app/foodylab/domain/discount/RateDiscountPolicy.java
  src/main/java/app/foodylab/domain/payment/DiscountPriceCalculateService.java
  src/test/java/app/foodylab/application/payment/service/PayServiceTest.java
  src/test/java/app/foodylab/domain/coupon/domain/CouponTest.java
Labels: 리팩토링
